spring:
  application:
    name: chat-storage-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:chat_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8082

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000}

logging:
  level:
    root: INFO

management:
  health:
      readinessstate:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true